= Couchbase Connect 2016 Developer Workshop

The workshop will show developers how to build a full-stack CRUD application with Couchbase server. Angular will be used for the frontend. Application code will be written using Java, Node or .NET. Couchbase will be used as the backend database. Couchbase will be used as the backend database.

Attendees will learn:

. Different options to install and basic configuration of Couchbase
. Data modeling for NoSQL applications
. Basic N1QL syntax to manipulate data
. Use Couchbase SDK to perform CRUD operations
. Couchbase SDK design patterns and anti-patterns
. Effective use of developer tools such as Query Workbench and Couchbase CLI
. Create a simple Couchbase cluster using Docker and on cloud platforms such as Amazon and Azure

=== Target Audience

Broad range of developers interested in using Couchbase

=== Requirements

* Reliable wifi for the AWS/Cloud workshop
* Thumb drives to distribute installation files/source code

== Install and Configure Couchbase

In this workshop, we will be learning how to do a simple installation of Couchbase Server. We will be going from nothing
to a single node cluster. Instructions will be provided for a local install on Windows, OS X, and Ubuntu 12/14 Linux distros.
We will also cover the creation of a Couchbase Server instance on the popular cloud hosting platforms AWS and Azure.
Finally, we will go over a single node installation in a Docker container (using Docker, Docker for Windows, or Docker for Mac).
When this session is complete, you will be ready for the next workshop.

* Running on Desktop
* Running on AWS / Azure
* Running on Docker

== Getting Familiar with Couchbase

In this workshop, we will be going over some basic developer interactions with Couchbase Server. You'll learn about how
to write and execute basic N1QL (SQL for JSON) queries in both the new Query Workbench and the cbq command line utility.
We will also write a very simple program using the Couchbase SDK. This program will create a new document and store it in
Couchbase, and it will also execute a N1QL query and display the results. Instructions will be provided for popular programming
languages including: Java, Node.js, and .NET.

* Query Workbench / cbq
* SDK Sample (.NET / Java / Node / maybe PHP)

== Building a Full-stack Application

In this workshop, we will be building a full stack web application. We will be using Angular to create the UI, and it will
make REST calls to a backend that interacts with Couchbase Server. Popular frameworks and languages will be covered, including
ASP.NET WebAPI, Express.js, and Spring. We will continue discussing N1QL, and we'll also look at basic data modeling. Finally, we
will look at some common design patterns for using the SDK in popular languages including: Java, Node.js, and .NET.

* Use an Angular frontend
* Use .NET / Node / Java backend (maybe PHP)
* Discuss data modeling
* N1QL
* SDK design patterns: async, timeouts, error handling, scan consistency (more?)

== Sample Couchbase Cluster

In this workshop, we will create a simple Couchbase Server cluster with multiple nodes. We will create a three node cluster
through using Docker containers, and popular cloud services AWS and Azure. Instructions will be provided for doing this with
your choice of Docker, Amazon, or Azure.

* Simple Docker cluster
* Simple Amazon cluster
* Simple Azure cluster

